odygrd/quill

quill/quill/src/detail/misc/Os.cpp
Allows the library to be compiled on MinGW at the loss of thread-naming feature. Not sure how critical that feature is tbh. Only affects MinGW.
=> MinGW compatibility.

quill/src/detail/misc/StringFromTime.cpp
Fixes the following warning when compiling with clang 11/12 on macOS:
```
[11/29] Building CXX object quill/CMakeFiles/quill.dir/src/detail/misc/StringFromTime.cpp.o
../quill/src/detail/misc/StringFromTime.cpp:191:19: warning: loop variable 'index' of type 'const std::__1::pair<unsigned long, quill::detail::StringFromTime::format_type>' creates a copy from type 'const std::__1::pair<unsigned long, quill::detail::StringFromTime::format_type>' [-Wrange-loop-analysis]
for (auto const index : _cached_indexes)
^
../quill/src/detail/misc/StringFromTime.cpp:191:8: note: use reference type 'const std::__1::pair<unsigned long, quill::detail::StringFromTime::format_type> &' to prevent copying
for (auto const index : _cached_indexes)
^~~~~~~~~~~~~~~~~~
&
1 warning generated.
```
=> Fix warning when compiling with clang on macOS

quill/include/quill/bundled/fmt/chrono.h, quill/src/detail/misc/Os.cpp
also include a minor fix: initialise dispatcher::tm_ in chrono.h
=> fix WIN32 compilation error when NOMINMAX is already defined

CMakeLists.txt, quill/src/detail/misc/Os.cpp, quill/test/UtilitiesTest.cpp
Add QUILL_NO_THREAD_NAME_SUPPORT CMAKE build option to prevent usage of SetThreadDescription API
Use of SetThreadDescription() only works in Windows 2019 server.
Issue (#113)
=> SetThreadDescription() API is not supported on older windows servers.

quill/include/quill/detail/LogManager.h, quill/include/quill/detail/ThreadContext.h, quill/include/quill/handlers/Handler.h
Some initializations using {} did not work when compiled with C++17
=> Fix initializations for C++17

quill/include/quill/Logger.h
One of the overloads of the check_format function names one of its
parameters but never uses it. This causes a compiler warning to be
emitted.
=> Fix compiler warning in check_format function

quill/include/quill/Logger.h, quill/include/quill/TweakMe.h, quill/include/quill/detail/ThreadContext.h, quill/include/quill/detail/backend/BackendWorker.h, quill/src/detail/ThreadContextCollection.cpp
Fixes #131: All options in TweakMe.h should be disabled by default. Otherwise options can not be enabled from the command line or cmake. This PR replaces QUILL_DUAL_QUEUE_MODE with QUILL_DISABLE_DUAL_QUEUE_MODE, which is disabled by default.
=> Replacing QUILL_DUAL_QUEUE_MODE with QUILL_DISABLE_DUAL_QUEUE_MODE

quill/src/detail/SignalHandler.cpp
If the code is compiled with QUILL_DISABLE_NON_PREFIXED_MACROS, quill
fails to compile because it's using the non-prefixed macros in its own
code.
This commit changes the code to use the prefixed macros.
=> Use QUILL-prefixed logging macros in quill

quill/include/quill/detail/ThreadContext.h
The _pad0 field of ThreadContext is unused and causes a compiler warning
to be emitted with clang.
This commit suppresses the warning for clang.
=> Fix compile warning in ThreadContext.h

quill/include/quill/MacroMetadata.h
Initialization order was incorrect on windows. The code does not compile if you have "treat warnings as errors" set.
=> Fix msvc compiler warning C5038 in MacroMetadata

quill/include/quill/MacroMetadata.h
MinGW generates paths with forward slashes in `__FILE__`. 
However, `fs::path::preferred_separator` is set to `\\` on Windows.
This is a fix to allow both separators to work.
This is ok as `/` is the ["portable separator"](https://en.cppreference.com/w/cpp/filesystem/path):
=> Fix forward slashes not working on Windows

quill/include/quill/MacroMetadata.h, quill/test/MacroMetadataTest.cpp
I'd like to format my messages with the following pattern : `"%(ascii_time) [%(logger_name)] [%(level_name)]: %(message)"`
But since the log levels strings contains trailing spaces, I get the following output :
```
01/28/23 12:37:06.275 [Output] [TRACE_L3 ]: 41
01/28/23 12:37:06.275 [Output] [TRACE_L2 ]: 18467
01/28/23 12:37:06.275 [Output] [TRACE_L1 ]: 6334
01/28/23 12:37:06.275 [Output] [DEBUG    ]: 26500
01/28/23 12:37:06.275 [Output] [INFO     ]: 19169
01/28/23 12:37:06.275 [Output] [WARNING  ]: 15724
01/28/23 12:37:06.275 [Output] [ERROR    ]: 11478
01/28/23 12:37:06.275 [Output] [CRITICAL ]: 29358
```
I understand those trailing spaces are here for aligning, but since the pattern string is converted to a fmt format string, I think it is better to remove the spaces from the log …
=> Remove trailing spaces in log levels strings

quill/src/detail/misc/Os.cpp
Quill cannot be used in any of the windows versions in the title as it uses GetThreadDescription and SetThreadDescription directly.
The limitiation is also mentioned at https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getthreaddescription: `Windows Server 2016, Windows 10 LTSB 2016 and Windows 10 version 1607: GetThreadDescription is only available by [Run Time Dynamic Linking](https://learn.microsoft.com/en-us/windows/win32/dlls/using-run-time-dynamic-linking) in KernelBase.dll.`
This merge request fixes that as Set/GetThreadDescription can be used with LoadLibrary.
Github doesn't allow me to upload a screenshot to this issue, but if you run an exe on Windows Server 2016 which is build with quill it will say
"The procedure entry point …
=> Support 'Windows Server 2016, Windows 10 LTSB 2016 and Windows 10 version 1607'

quill/src/detail/misc/Os.cpp
My previous pull request didn't free libraries in case of an error in 'GetProcAddress'.
This should fix it.
=> Fix memory leak from 'Support 'Windows 10 LTSB 2016, 1607 and Server 2016'

quill/include/quill/detail/misc/Rdtsc.h
```
In file included from /Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/quill/2.9.0/_/_/build/182ec311e04295bce36a12820ce7004d2a380991/src/quill/src/detail/backend/BackendWorker.cpp:1:
In file included from /Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/quill/2.9.0/_/_/build/182ec311e04295bce36a12820ce7004d2a380991/src/quill/include/quill/detail/backend/BackendWorker.h:13:
In file included from /Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/quill/2.9.0/_/_/build/182ec311e04295bce36a12820ce7004d2a380991/src/quill/include/quill/detail/LoggerCollection.h:9:
In file included from /Users/jenkins/w/prod/BuildSingleReference@2/.conan/data/quill/2.9.0/_/_/build/182ec311e04295bce36a12820ce7004d2a380991/src/quill/include/quill/Logger.h:18: …
```
=> Fix compile warning on Apple M1

quill/include/quill/Quill.h, quill/src/Quill.cpp
A minor change, but seems very reasonable and allows `quill::configure(quill::Config{});`
=> pass Config by const reference to quill::configure()

docs/tutorial.rst
As of https://github.com/odygrd/quill/pull/277, handlers are shared pointers rather than raw pointers.
=> Update tutorial to use shared pointer for handlers

quill/include/quill/detail/misc/Rdtsc.h
Intel Compiler Classic itself doesn't have x86gprintrin.h and it seems incompatible with GCC's x86gprintrin.h
So the following code in quill/detail/misc/Rdtsc.h (line 18) will cause a build error.
```
#if defined(_WIN32)
#include <intrin.h>
#elif (defined(__GNUC__) && __GNUC__ > 10) || (defined(__clang_major__) && __clang_major__ > 11)
#include <x86gprintrin.h>
#else
// older compiler versions do not have <x86gprintrin.h>
#include <x86intrin.h>
#endif
```
This problem does not occur with the current Intel Compiler which is not Classic.
I hope you will take this into consideration because there are users like me.
Reproduce snipet by godbolt is here.
https://godbolt.org/z/Yx7vqsvEb
=> fix build failure of Intel Compiler Classic

quill/src/handlers/RotatingFileHandler.cpp
Previously '_created_files' sometimes stored the full path and sometimes only the filename. This PR fixes that.
The problem is that the logfile is not always located in the working directory.
Basically quill::detail::rename_file() failed sometimes in _rotate_files() and showed an error on the console for the filename-only-files.
Also changed the hardcoded .log extension to fs::extension(). ;)
=> RotatingFileHandler: Store complete path in '_created_files'

quill/include/quill/Logger.h
This is pretty minor but it would be useful for me. My use case is that I've implemented log level inheritance as a function of logger names, like log4cxx and (I think) log4j have. E.g., if you set the log level for logger "foo", then all loggers named "foo.xyz" for any xyz will automatically use the same log level as logger "foo".
If I had to, I could keep track of the logger names myself, via e.g. map<quill::Logger*, std::string> but since the Logger already has its name this seemed reasonable and obviously much more ergonomic for my case.
I considered adding accessors for some of the other things in LoggerDetails, but decided against it since I don't currently have any need for them.
=> added accessor method for Logger name

quill/cmake/quill.pc.in
while trying to add this library to nixpkgs, I got this error:
```
Broken paths found in a .pc file! /nix/store/dl9q6b8qiglsd29fi9dg9y0byqzgmjmq-quillcpp-3.3.1/pkgconfig/quill.pc
The following lines have issues (specifically '//' in paths).
4:libdir=${exec_prefix}//nix/store/dl9q6b8qiglsd29fi9dg9y0byqzgmjmq-quillcpp-3.3.1/lib
5:includedir=${prefix}//nix/store/dl9q6b8qiglsd29fi9dg9y0byqzgmjmq-quillcpp-3.3.1/include
It is very likely that paths are being joined improperly.
ex: "${prefix}/@CMAKE_INSTALL_LIBDIR@" should be "@CMAKE_INSTALL_FULL_LIBDIR@"
Please see https://github.com/NixOS/nixpkgs/issues/144170 for more details.
```
builds fine after this commit, checked the file and the paths are correct on nix so this shouldn't break anything
=> fix lib and include paths

examples/example_trivial.cpp, quill/include/quill/detail/Serialize.h, quill/include/quill/detail/misc/TypeTraitsCopyable.h, quill/test/LogTest.cpp, quill/test/TypeTraitsCopyableTest.cpp
quill treats c array as c string and use `strlen()` to get the size of the c array buffer, which is not safe if the c array contain no `\0` at all.
this patch uses `strnlen()` and array size to fix this issue #351
=> better char array support

docs/install.rst
The "Building and Installing Quill"  step-by-step CLI example was missing the `cmake ..` invocation to create the Makefile for the next make step.
=> Add missing cmake invocation install.rst

docs/tutorial.rst
I was reading through parts of the docs and copy pasted some examples to run. some of them didn't compile, I think this namespace change is a step in the right direction for the docs :)
=> Update namespaces in tutorial.rst

quill/include/quill/Logger.h, quill/test/LoggerTest.cpp
Thanks for merging the previous PR to add Logger::name(). It looks like the method was made private during the merge, probably by accident (note that there are two separate 'private:' keywords in the declaration of Logger).
I made it public and added a case to LoggerTest.cpp to ensure that it's accessible.
=> made Logger::name() public, added test case

quill/src/detail/SignalHandler.cpp
Compile Fix in SignalHandler on Windows, if QUILL_DISABLE_NON_PREFIXED_MACROS is defined in TweakMe.h
=> Compile fix SignalHandler on Windows

benchmarks/hot_path_latency/hot_path_bench.h
`sched_setaffinity` might return an error on attempt to set affinity beyond CPU cores limit. It makes `BENCHMARK_quill_hot_path_system_clock` and `BENCHMARK_quill_hot_path_rdtsc_clock` test fails with `"failed to call set_cpu_affinity"` exception. 
Bug fires on systems with small cpu count (tested on 2-core instance).
=> Fix hot_path benchmark on systems with small cpu count.

quill/include/quill/detail/Serialize.h
This PR fixes Windows clang-cl build error: "constexpr variable 'strnlen' must be initialized by a constant expression. "
Unfortunately the strnlen() seems incompatible with constexpr in clang-cl compile.
But in the case of this case, MSVC/clang-cl can use the strnlen_s() function anyway.
This changes should only affects the Windows MSVC/clang-cl build.
descrived in #399
=> fix windows clang-cl build error #399

quill/src/detail/misc/Os.cpp
This PR fixes compilation errors on FreeBSD and adds support for several other BSD operating systems to get_thread_id() function.
=> Add get_thread_id implementations for BSDs.

quill/src/handlers/ConsoleHandler.cpp
When using a dynamic log level, ConsoleHandler::write() needs to get the log level by calling TransitEvent::log_level() instead of directly accessing the log level stored in MacroMetaData.
MacroMetadata::_log_level could be LogLevel::Dynamic, which will result in an out of bounds array access in ConsoleColours::colour_code().
Prior to this change, ConsoleHandler::write() was apparently not using the correct colour value for a dynamic log level (unless by accident).
=> ConsoleHandler: fix for out of bounds array access with dynamic log level and coloured console output

examples/tags_logging.cpp
Invalid format pattern, attribute with name "custom_tags" is invalid
=> fix: custom_tags => tags

test/unit_tests/CMakeLists.txt
I see some of the tests have a name inconsistent to the convention used for the other tests.
This should be the fix.
=> Fix inconsistent test names

docs/installing.rst
update cmake instructions with missing 'cd quill' command
=> fix cmake instructions

examples/shared_library/example_shared.cpp, examples/shared_library/quill_wrapper_shared/include/quill_wrapper_shared/quill_wrapper_shared.cpp, examples/shared_library/quill_wrapper_shared/include/quill_wrapper_shared/quill_wrapper_shared.h
=> update example to ensure build fails in the future for similar linkage error

CMakeLists.txt, include/quill/core/BoundedSPSCQueue.h
Importing `quill` source code as part of a larger project can reveal points of improvement mainly pointed out by inherited compiler flags. Fixes include:
- Tolerate float comparison when using equality operator.   
```
comparing floating point with == or != is unsafe [-Werror,-Wfloat-equal]
```
- Improve implicit conversion to avoid lose of precision (hopefully multiplication result falls in the original author's error tolerance intention).
```
implicit conversion from 'const integer_type' (aka 'const unsigned long') to 'double' may lose precision [-Werror,-Wimplicit-int-float-conversion]
```
- Modern CMake versions (e.g. `3.31.5`) can reveal obsolete CMake policy incompatibility. Changing minimum version to `3.10` alleviates these warnings. Worth noting that current version `3.8` dates …
=> Improve variable conversion & comparison handling as well as CMake version compatibility

include/quill/backend/BackendUtilities.h, include/quill/backend/BackendWorker.h, include/quill/backend/RdtscClock.h, include/quill/backend/ThreadUtilities.h, include/quill/core/Attributes.h, include/quill/core/BoundedSPSCQueue.h, include/quill/core/Common.h, include/quill/core/InlinedVector.h, include/quill/core/MacroMetadata.h, include/quill/core/ThreadContextManager.h, include/quill/core/UnboundedSPSCQueue.h
Some issues I found while trying to build for freebsd.
There were not many of them but the funniest one was `CACHE_LINE_SIZE` which is defined in freebsd header so there is a conflict.
Wasn't sure if you insist for uppercase for constants, I saw some constants in lowercase so I opted for this solution.
=> Fix FreeBSD build

include/quill/sinks/FileSink.h
Change the default open mode of FileSink to be 'a' to make it match the comment.
The comment says the default open mode is 'a' but actually it is 'w'...
I think most people do not like the log file be overwritten to empty in every restart. Correct it be 'a' again.
=> Change the default open mode of FileSink to be 'a'

include/quill/core/LoggerManager.h
Added check to ensure logger_ptr is not null. logger_ptr is set to _find_logger and there is a possibility for this function to return nullptr.
```cpp 
return (search_it != std::end(_loggers) && search_it->get()->get_logger_name() == target)
? search_it->get()
: nullptr;
```
=> Added a fix in create_or_get_logger function to check logger_ptr prior to use (#748)

include/quill/StringRef.h, include/quill/core/Codec.h, include/quill/core/Common.h, test/unit_tests/UnboundedQueueTest.cpp
With CI/CD enabled on salsa i386 build failed. Problem was identified in a test and library files. For the test a conditional compilation flag was introduce to differential between 32bit and 64bit platforms. While in the library the problem was due to **std::memchr** "max number of bytes to examine" set to maximum size of unsigned int which does not work on i386 platform.
=> Fix for failing i386 build #753

include/quill/sinks/RotatingSink.h
Debian packaging 1 test failed due time_t size on i386.
Within _calculate_initial_rotation_tp function time_now value results in zero due to out of range value casting to time_t. 
Reference:
Job: https://debusine.debian.net/debian/developers/artifact/2153871/#L5754-files
Pipeline: https://debusine.debian.net/debian/developers/work-request/127768/
=> Fix for i386 time_t within calculate initial rotation tp #669.

cmake/QuillUtils.cmake, test/integration_tests/CMakeLists.txt
This method is chosen for fixing armel atomic linking error for CMake  project due to order of libraries. Placing the library linking prior to file does not works as explained on https://github.com/scipy/scipy/issues/19982#issuecomment-1925322060
=> Fix armel atomic linking error #669.

CHANGELOG.md, include/quill/backend/RdtscClock.h
The current lag thresholds are very tight, it would make sense to relax them a bit
=> Increase `RdtscClock` resync lag thresholds
